---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: hello-params-run
spec:
  serviceAccountName: harbor-sa
  taskRef:
    name: hello-params
  params:
  - name: target
    value: "dengyouf"
