---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
---


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
---